### ISSUE TITLE
Please bump version of xml package version in tentacle_response_formatter, and then bump tentacle in shelf_exception_response

### ISSUE THREAD

**Issue by jonaskello** [octobyte/shelf_exception_response#4]
Our app needs xml package version 2.2.3 and use shelf_expection_response but this is not possible because:

shelf_exception_response depends on tentacle_respnonse_formatter that depends on xml: ">=1.0.0 <2.0.0". Please bump the dependency chain up to use xml 2.2.3.

**Comment by tompro** [comment]
with https://github.com/octobyte/shelf_exception_response/issues/6 this should be using shelf_response_formatter
